services:
  web:
    image: docker.io/wger/server:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      SECRET_KEY: ${WGER_SECRET_KEY}
      SITE_URL: ${WGER_SITE_URL}
      TIME_ZONE: Europe/Zurich
      TZ: Europe/Zurich
      DJANGO_DB_ENGINE: django.db.backends.postgresql
      DJANGO_DB_DATABASE: wger
      DJANGO_DB_USER: wger
      DJANGO_DB_PASSWORD: ${WGER_DB_PASSWORD}
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: "5432"
      POSTGRES_USER: wger
      POSTGRES_PASSWORD: ${WGER_DB_PASSWORD}
      POSTGRES_DB: wger
      PS_DATABASE_URI: postgres://wger:${WGER_DB_PASSWORD}@db:5432/wger
      DJANGO_PERFORM_MIGRATIONS: "True"
      WGER_INSTANCE: https://wger.de
      ALLOW_REGISTRATION: ${WGER_ALLOW_REGISTRATION}
      ALLOW_GUEST_USERS: "False"
      ALLOW_UPLOAD_VIDEOS: "True"
      MIN_ACCOUNT_AGE_TO_TRUST: "21"
      SYNC_EXERCISES_CELERY: "True"
      SYNC_EXERCISE_IMAGES_CELERY: "True"
      SYNC_EXERCISE_VIDEOS_CELERY: "True"
      SYNC_INGREDIENTS_CELERY: "True"
      SYNC_INGREDIENTS_DUMP_URL: https://wger.de/media/ingredients/ingredients.jsonl.gz
      DOWNLOAD_INGREDIENTS_FROM: WGER
      CACHE_API_EXERCISES_CELERY: "True"
      CACHE_API_EXERCISES_CELERY_FORCE_UPDATE: "True"
      USE_CELERY: "True"
      CELERY_BROKER: redis://cache:6379/2
      CELERY_BACKEND: redis://cache:6379/2
      CELERY_FLOWER_PASSWORD: adminadmin
      CELERY_WORKER_CONCURRENCY: "4"
      DJANGO_CACHE_BACKEND: django_redis.cache.RedisCache
      DJANGO_CACHE_LOCATION: redis://cache:6379/1
      DJANGO_CACHE_TIMEOUT: "1296000"
      DJANGO_CACHE_CLIENT_CLASS: django_redis.client.DefaultClient
      AXES_ENABLED: "True"
      AXES_FAILURE_LIMIT: "10"
      AXES_COOLOFF_TIME: "30"
      AXES_HANDLER: axes.handlers.cache.AxesCacheHandler
      AXES_LOCKOUT_PARAMETERS: ip_address
      AXES_IPWARE_PROXY_COUNT: "1"
      AXES_IPWARE_META_PRECEDENCE_ORDER: HTTP_X_FORWARDED_FOR,REMOTE_ADDR
      DJANGO_DEBUG: "False"
      WGER_USE_GUNICORN: "True"
      EXERCISE_CACHE_TTL: "2419200"
      WGER_PORT: "8000"
      ACCESS_TOKEN_LIFETIME: "10"
      REFRESH_TOKEN_LIFETIME: "2880"
      LOG_LEVEL_PYTHON: INFO
      USE_RECAPTCHA: "False"
      DJANGO_CLEAR_STATIC_FIRST: "False"
      DJANGO_COLLECTSTATIC_ON_STARTUP: "True"
      FROM_EMAIL: "wger Workout Manager <wger@example.com>"
      NUMBER_OF_PROXIES: "1"
      GUNICORN_CMD_ARGS: "--workers 3 --threads 2 --worker-class gthread --timeout 240"
      EXPOSE_PROMETHEUS_METRICS: "False"
    volumes:
      - static:/home/wger/static
      - media:/home/wger/media
    expose:
      - 8000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      start_period: 300s
      retries: 5
    restart: unless-stopped

  powersync:
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_healthy
    restart: unless-stopped
    image: docker.io/journeyapps/powersync-service:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    command: ["start", "-r", "unified"]
    volumes:
      - ./services/config-powersync:/config:ro
    environment:
      POWERSYNC_CONFIG_PATH: /config/powersync.yaml
      PS_JWKS_URL: http://web:8000/api/v2/powersync-keys
      PS_DATABASE_URI: postgres://wger:${WGER_DB_PASSWORD}@db:5432/wger
      PS_STORAGE_PG_URI: postgres://powersync_storage:powersync_password@db:5432/wger
      PS_PORT: "8080"
      POWERSYNC_URL_PATH: ps
    expose:
      - 8080
      - 9090

  nginx:
    image: docker.io/nginx:stable
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    depends_on:
      - web
      - powersync
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/wger/static:ro
      - media:/wger/media:ro
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  db:
    image: docker.io/postgres:15-alpine
    shm_size: 256mb
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    environment:
      POSTGRES_USER: wger
      POSTGRES_PASSWORD: ${WGER_DB_PASSWORD}
      POSTGRES_DB: wger
      TZ: Europe/Zurich
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    command: [
      "postgres",
      "-c", "wal_level=logical",
      "-c", "shared_buffers=256MB",
      "-c", "effective_cache_size=768MB",
      "-c", "work_mem=8MB",
      "-c", "random_page_cost=1.1",
      "-c", "max_connections=30"
    ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  cache:
    image: docker.io/redis
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    expose:
      - 6379
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  celery_worker:
    image: docker.io/wger/server:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    command: /start-worker
    environment:
      SECRET_KEY: ${WGER_SECRET_KEY}
      SITE_URL: ${WGER_SITE_URL}
      TIME_ZONE: Europe/Zurich
      TZ: Europe/Zurich
      DJANGO_DB_ENGINE: django.db.backends.postgresql
      DJANGO_DB_DATABASE: wger
      DJANGO_DB_USER: wger
      DJANGO_DB_PASSWORD: ${WGER_DB_PASSWORD}
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: "5432"
      POSTGRES_USER: wger
      POSTGRES_PASSWORD: ${WGER_DB_PASSWORD}
      POSTGRES_DB: wger
      DJANGO_PERFORM_MIGRATIONS: "True"
      USE_CELERY: "True"
      CELERY_BROKER: redis://cache:6379/2
      CELERY_BACKEND: redis://cache:6379/2
      CELERY_WORKER_CONCURRENCY: "4"
      DJANGO_CACHE_BACKEND: django_redis.cache.RedisCache
      DJANGO_CACHE_LOCATION: redis://cache:6379/1
      DJANGO_CACHE_CLIENT_CLASS: django_redis.client.DefaultClient
      SYNC_EXERCISES_CELERY: "True"
      SYNC_EXERCISE_IMAGES_CELERY: "True"
      SYNC_EXERCISE_VIDEOS_CELERY: "True"
      SYNC_INGREDIENTS_CELERY: "True"
      SYNC_INGREDIENTS_DUMP_URL: https://wger.de/media/ingredients/ingredients.jsonl.gz
      DOWNLOAD_INGREDIENTS_FROM: WGER
      CACHE_API_EXERCISES_CELERY: "True"
      CACHE_API_EXERCISES_CELERY_FORCE_UPDATE: "True"
      DJANGO_DEBUG: "False"
    volumes:
      - media:/home/wger/media
    depends_on:
      web:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "celery", "-A", "wger", "inspect", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  celery_beat:
    image: docker.io/wger/server:latest
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 3
    command: /start-beat
    volumes:
      - celery-beat:/home/wger/beat/
    environment:
      SECRET_KEY: ${WGER_SECRET_KEY}
      SITE_URL: ${WGER_SITE_URL}
      TIME_ZONE: Europe/Zurich
      TZ: Europe/Zurich
      DJANGO_DB_ENGINE: django.db.backends.postgresql
      DJANGO_DB_DATABASE: wger
      DJANGO_DB_USER: wger
      DJANGO_DB_PASSWORD: ${WGER_DB_PASSWORD}
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: "5432"
      POSTGRES_USER: wger
      POSTGRES_PASSWORD: ${WGER_DB_PASSWORD}
      POSTGRES_DB: wger
      DJANGO_PERFORM_MIGRATIONS: "True"
      USE_CELERY: "True"
      CELERY_BROKER: redis://cache:6379/2
      CELERY_BACKEND: redis://cache:6379/2
      DJANGO_DEBUG: "False"
    depends_on:
      celery_worker:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres-data:
  celery-beat:
  redis-data:
  media:
  static:
